
package View;

/**
 *
 * @author brandonworley
 */
public class CreateCustomerUI extends javax.swing.JPanel {

    /**
     * Creates new form CreateCustomer
     */
    public CreateCustomerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFistName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        lblCreateUserTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblSaveAccountError = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(300, 590));
        setName("createCustPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 590));
        setVerifyInputWhenFocusTarget(false);

        lblFistName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblFistName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFistName.setText("First Name:");
        lblFistName.setName("lblFirstName"); // NOI18N

        lblLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLastName.setText("Last Name: ");
        lblLastName.setName("lblLastName"); // NOI18N

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail.setText("E-Mail:");
        lblEmail.setName("lblEmail"); // NOI18N

        tfFirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfFirstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFirstName.setName("tfFirstName"); // NOI18N

        tfLastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfLastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfLastName.setName("tfLastName"); // NOI18N

        tfEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfEmail.setToolTipText("");
        tfEmail.setName("tfEmail"); // NOI18N

        lblCreateUserTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreateUserTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateUserTitle.setText("Create Account");
        lblCreateUserTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username:");
        lblUsername.setName("lblUsername"); // NOI18N

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password:");
        lblPassword.setName("lblPassword"); // NOI18N

        tfUsername.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUsername.setName("tfUsername"); // NOI18N

        tfPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tfPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfPassword.setName("tfPassword"); // NOI18N

        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSave.setName("btnSave"); // NOI18N

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setActionCommand("");
        btnCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancel.setName("btnCancel"); // NOI18N

<<<<<<< Updated upstream
        lblSaveAccountError.setForeground(new java.awt.Color(255, 0, 0));
        lblSaveAccountError.setText("User Name is not available");
        lblSaveAccountError.setName("lblSaveAccountError"); // NOI18N
=======
<<<<<<< HEAD
        lblSaveAccountError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaveAccountError.setForeground(new java.awt.Color(255, 0, 51));
        lblSaveAccountError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaveAccountError.setText("Error Message");
=======
        lblSaveAccountError.setForeground(new java.awt.Color(255, 0, 0));
        lblSaveAccountError.setText("User Name is not available");
        lblSaveAccountError.setName("lblSaveAccountError"); // NOI18N
>>>>>>> d40cd12a9894920b18175232ddb29f37eec36a4d
>>>>>>> Stashed changes

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFistName)
                    .addComponent(lblEmail)
                    .addComponent(lblCreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLastName)
<<<<<<< HEAD
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfUsername)
                                        .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSaveAccountError, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(4, Short.MAX_VALUE))
=======
                                .addComponent(lblUsername)
                                .addComponent(lblPassword))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfLastName)
                                .addComponent(tfUsername)
                                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(87, 87, 87)
                        .addComponent(btnCancel)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSaveAccountError)
                        .addGap(168, 168, 168))))
<<<<<<< Updated upstream
=======
>>>>>>> d40cd12a9894920b18175232ddb29f37eec36a4d
>>>>>>> Stashed changes
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFistName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblSaveAccountError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< Updated upstream
=======
<<<<<<< HEAD
                .addGap(18, 18, 18)
                .addComponent(lblSaveAccountError, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(199, Short.MAX_VALUE))
=======
>>>>>>> Stashed changes
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(187, Short.MAX_VALUE))
<<<<<<< Updated upstream
=======
>>>>>>> d40cd12a9894920b18175232ddb29f37eec36a4d
>>>>>>> Stashed changes
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCreateUserTitle;
    private javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblFistName;
    public javax.swing.JLabel lblLastName;
    public javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblSaveAccountError;
    public javax.swing.JLabel lblUsername;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfFirstName;
    public javax.swing.JTextField tfLastName;
    public javax.swing.JTextField tfPassword;
    public javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
