/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 * This class is used to display the user interface for the main navigation menu.
 * @author Kate
 */
public class NavigationUI extends javax.swing.JPanel {

    /**
     * Creates new form NavigationUI
     */
    public NavigationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountInformationButton = new javax.swing.JButton();
        parkInformationButton = new javax.swing.JButton();
        purchaseTicketsButton = new javax.swing.JButton();
        manageReservationsButton = new javax.swing.JButton();
        manageFoodOrdersButton = new javax.swing.JButton();
        manageReports = new javax.swing.JButton();
        navigationPanelTitleLabel = new javax.swing.JLabel();
        exitApplicationButton = new javax.swing.JButton();
        viewItineraryButton = new javax.swing.JButton();
        purchaseTicketsButton1 = new javax.swing.JButton();

        accountInformationButton.setText("Account Information");
        accountInformationButton.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                accountInformationButtonComponentAdded(evt);
            }
        });
        accountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInformationButtonActionPerformed(evt);
            }
        });

        parkInformationButton.setText("Park Information");
        parkInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkInformationButtonActionPerformed(evt);
            }
        });

        purchaseTicketsButton.setText("Purchase Tickets");
        purchaseTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTicketsButtonActionPerformed(evt);
            }
        });

        manageReservationsButton.setText("Manage Reservations");
        manageReservationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReservationsButtonActionPerformed(evt);
            }
        });

        manageFoodOrdersButton.setText("Manage Food Orders");
        manageFoodOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFoodOrdersButtonActionPerformed(evt);
            }
        });

        manageReports.setText("Manage Reports");
        manageReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageReportsActionPerformed(evt);
            }
        });

        navigationPanelTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        navigationPanelTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        navigationPanelTitleLabel.setText("Main Navigation Menu");

        exitApplicationButton.setText("Exit Application");
        exitApplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitApplicationButtonActionPerformed(evt);
            }
        });

        viewItineraryButton.setText("View Itinerary");
        viewItineraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItineraryButtonActionPerformed(evt);
            }
        });

        purchaseTicketsButton1.setText("Manage Tickets");
        purchaseTicketsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTicketsButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationPanelTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitApplicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(accountInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parkInformationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseTicketsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageReservationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageFoodOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewItineraryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchaseTicketsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigationPanelTitleLabel)
                .addGap(14, 14, 14)
                .addComponent(accountInformationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parkInformationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseTicketsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchaseTicketsButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageReservationsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageFoodOrdersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewItineraryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitApplicationButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void parkInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkInformationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parkInformationButtonActionPerformed

    private void exitApplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitApplicationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitApplicationButtonActionPerformed

    private void accountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInformationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountInformationButtonActionPerformed

    private void accountInformationButtonComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_accountInformationButtonComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_accountInformationButtonComponentAdded

    private void purchaseTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTicketsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseTicketsButtonActionPerformed

    private void manageReservationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReservationsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageReservationsButtonActionPerformed

    private void manageFoodOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFoodOrdersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageFoodOrdersButtonActionPerformed

    private void viewItineraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItineraryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewItineraryButtonActionPerformed

    private void manageReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageReportsActionPerformed

    private void purchaseTicketsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTicketsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseTicketsButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInformationButton;
    private javax.swing.JButton exitApplicationButton;
    private javax.swing.JButton manageFoodOrdersButton;
    private javax.swing.JButton manageReports;
    private javax.swing.JButton manageReservationsButton;
    private javax.swing.JLabel navigationPanelTitleLabel;
    private javax.swing.JButton parkInformationButton;
    private javax.swing.JButton purchaseTicketsButton;
    private javax.swing.JButton purchaseTicketsButton1;
    private javax.swing.JButton viewItineraryButton;
    // End of variables declaration//GEN-END:variables
}
