/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 * This class is to provide the user interface for purchasing park tickets.
 * @author Kate
 */
public class PurchaseTickets extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseTickets
     */
    public PurchaseTickets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseTicketsTitleLabel = new javax.swing.JLabel();
        ticketPurchaseInformationLabel = new javax.swing.JLabel();
        numberOfTicketsTextField = new javax.swing.JTextField();
        numberOfTicketsLabel = new javax.swing.JLabel();
        numberOfDaysLabel = new javax.swing.JLabel();
        numberOfDaysTextField = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        totalCostLabel = new javax.swing.JLabel();
        subtotalValueLabel = new javax.swing.JLabel();
        totalCostValueLable = new javax.swing.JLabel();
        taxValueLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cancelPurchaseButton = new javax.swing.JButton();
        purchaseTicketsButton = new javax.swing.JButton();

        purchaseTicketsTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        purchaseTicketsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purchaseTicketsTitleLabel.setText("Purchase Tickets");

        ticketPurchaseInformationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ticketPurchaseInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ticketPurchaseInformationLabel.setText("Tickets cost $50 per person, per day.  Please select the quantity of tickets and number of days you want to purchase.");
        ticketPurchaseInformationLabel.setToolTipText("");

        numberOfTicketsTextField.setText("jTextField1");

        numberOfTicketsLabel.setText("Number of Tickets");

        numberOfDaysLabel.setText("Number of Days");

        numberOfDaysTextField.setText("jTextField1");

        subtotalLabel.setText("Subtotal");

        taxLabel.setText("Tax Amount");

        totalCostLabel.setText("Total Cost");

        subtotalValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subtotalValueLabel.setText("$0");

        totalCostValueLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalCostValueLable.setText("$0");

        taxValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxValueLabel.setText("$0");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cancelPurchaseButton.setText("Cancel");
        cancelPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPurchaseButtonActionPerformed(evt);
            }
        });

        purchaseTicketsButton.setText("Purchase Tickets");
        purchaseTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseTicketsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketPurchaseInformationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 88, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(taxValueLabel)
                                            .addComponent(totalCostValueLable)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(numberOfDaysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(numberOfTicketsLabel)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                        .addComponent(numberOfTicketsTextField)
                                                        .addComponent(numberOfDaysTextField)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(subtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(subtotalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(99, 99, 99))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cancelPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(purchaseTicketsButton)
                                        .addGap(57, 57, 57))))))
                    .addComponent(purchaseTicketsTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(purchaseTicketsTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketPurchaseInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfTicketsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfTicketsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfDaysLabel)
                    .addComponent(numberOfDaysTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalLabel)
                            .addComponent(subtotalValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxLabel)
                            .addComponent(taxValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCostLabel)
                            .addComponent(totalCostValueLable))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelPurchaseButton)
                            .addComponent(purchaseTicketsButton))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPurchaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelPurchaseButtonActionPerformed

    private void purchaseTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseTicketsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseTicketsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPurchaseButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel numberOfDaysLabel;
    private javax.swing.JTextField numberOfDaysTextField;
    private javax.swing.JLabel numberOfTicketsLabel;
    private javax.swing.JTextField numberOfTicketsTextField;
    private javax.swing.JButton purchaseTicketsButton;
    private javax.swing.JLabel purchaseTicketsTitleLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel subtotalValueLabel;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxValueLabel;
    private javax.swing.JLabel ticketPurchaseInformationLabel;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JLabel totalCostValueLable;
    // End of variables declaration//GEN-END:variables
}
