/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ActivityCtrl;
import Controller.NavigationCtrl;
import Model.Activity;
import java.util.ArrayList;

/**
 *
 * @author Kate
 */
public class ReserveActivityUI extends javax.swing.JFrame {
    Activity reservedActivity;
    ActivityCtrl activityCtrl;   
    private int counter = 0;
    private int maxCapacityRide = 10;
    private int maxCapacityShow = 50;
    /**
     * Creates new form ReserveActivityUI
     */
    public ReserveActivityUI() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlSelectActivityType = new javax.swing.JPanel();
        btnRide = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        lblSelectActivityType = new javax.swing.JLabel();
        btnMainMenuActSel = new javax.swing.JButton();
        pnlReserveRide = new javax.swing.JPanel();
        cbSelectRide = new javax.swing.JComboBox<>();
        cbSelectRideReservation = new javax.swing.JComboBox<>();
        lblReserveRideTitle = new javax.swing.JLabel();
        lblSelectRide = new javax.swing.JLabel();
        lblSelectRideReservation = new javax.swing.JLabel();
        btnRideReserve = new javax.swing.JButton();
        btnRideCancel = new javax.swing.JButton();
        spnRideResQty = new javax.swing.JSpinner();
        lblRideResError = new javax.swing.JLabel();
        lblSelectRideResQty = new javax.swing.JLabel();
        pnlReserveShow = new javax.swing.JPanel();
        cbSelectShow = new javax.swing.JComboBox<>();
        cbSelectShowReservation = new javax.swing.JComboBox<>();
        lblReserveShowTitle = new javax.swing.JLabel();
        lblSelectShow = new javax.swing.JLabel();
        lblSelectShowReservation = new javax.swing.JLabel();
        btnShowReserve = new javax.swing.JButton();
        btnShowCancel = new javax.swing.JButton();
        lblShowResError = new javax.swing.JLabel();
        spnShowResQty = new javax.swing.JSpinner();
        lblSelectShowResQty = new javax.swing.JLabel();
        pnlReservationConfirmation = new javax.swing.JPanel();
        lblReserveRideTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taActivityReservationInfo = new javax.swing.JTextArea();
        btnMainMenu = new javax.swing.JButton();
        lblConfirmedReservationInfo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        btnRide.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRide.setText("Ride");
        btnRide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRideActionPerformed(evt);
            }
        });

        btnShow.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnShow.setText("Show");
        btnShow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        lblSelectActivityType.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSelectActivityType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectActivityType.setText("Select an Activity Type");

        btnMainMenuActSel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMainMenuActSel.setText("Main Menu");
        btnMainMenuActSel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMainMenuActSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActSelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSelectActivityTypeLayout = new javax.swing.GroupLayout(pnlSelectActivityType);
        pnlSelectActivityType.setLayout(pnlSelectActivityTypeLayout);
        pnlSelectActivityTypeLayout.setHorizontalGroup(
            pnlSelectActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectActivityTypeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlSelectActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnShow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMainMenuActSel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblSelectActivityType, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        pnlSelectActivityTypeLayout.setVerticalGroup(
            pnlSelectActivityTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectActivityTypeLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblSelectActivityType)
                .addGap(23, 23, 23)
                .addComponent(btnRide, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMainMenuActSel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSelectActivityType);

        cbSelectRide.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbSelectRide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monster Coaster", "Kiddy Coaster", "3D Train Ride", "Tornado", "Shoot The Rapids" }));

        cbSelectRideReservation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbSelectRideReservation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:15 AM", "8:30 AM", "8:45 AM", "9:00 AM", "9:15 AM", "9:30 AM", "9:45 AM", "10:00 AM", "10:15 AM", "10:30 AM", "10:45 AM", "11:00 AM", "11:15 AM", "11:30 AM", "11:45 AM", "12:00 PM", "12:15 PM", "12:30 PM", "12:45 PM", "1:00 PM", "1:15 PM", "1:30 PM", "1:45 PM", "2:00 PM", "2:15 PM", "2:30 PM", "2:45 PM", "3:00 PM", "3:15 PM", "3:30 PM", "3:45 PM", "4:00 PM", "4:15 PM", "4:30 PM", "4:45 PM", "5:00 PM", "5:15 PM", "5:30 PM", "5:45 PM", "6:00 PM", "6:15 PM", "6:30 PM", "6:45 PM" }));

        lblReserveRideTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblReserveRideTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserveRideTitle.setText("Reserve a Ride");

        lblSelectRide.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectRide.setText("Select a Ride:");

        lblSelectRideReservation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectRideReservation.setText("Select a Ride Reservation:");

        btnRideReserve.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRideReserve.setText("Reserve");
        btnRideReserve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRideReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRideReserveActionPerformed(evt);
            }
        });

        btnRideCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRideCancel.setText("Cancel");
        btnRideCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRideCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRideCancelActionPerformed(evt);
            }
        });

        spnRideResQty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblRideResError.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRideResError.setForeground(new java.awt.Color(255, 0, 0));
        lblRideResError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRideResError.setText("Error Message");

        lblSelectRideResQty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectRideResQty.setText("Ride Reservation Quantity:");

        javax.swing.GroupLayout pnlReserveRideLayout = new javax.swing.GroupLayout(pnlReserveRide);
        pnlReserveRide.setLayout(pnlReserveRideLayout);
        pnlReserveRideLayout.setHorizontalGroup(
            pnlReserveRideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReserveRideTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addGroup(pnlReserveRideLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlReserveRideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbSelectRideReservation, 0, 217, Short.MAX_VALUE)
                    .addComponent(lblSelectRideReservation)
                    .addComponent(lblSelectRide)
                    .addGroup(pnlReserveRideLayout.createSequentialGroup()
                        .addComponent(btnRideCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRideReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbSelectRide, 0, 217, Short.MAX_VALUE)
                    .addComponent(lblSelectRideResQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReserveRideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlReserveRideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReserveRideLayout.createSequentialGroup()
                        .addComponent(spnRideResQty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReserveRideLayout.createSequentialGroup()
                        .addComponent(lblRideResError, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlReserveRideLayout.setVerticalGroup(
            pnlReserveRideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReserveRideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReserveRideTitle)
                .addGap(24, 24, 24)
                .addComponent(lblSelectRide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSelectRide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblSelectRideReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSelectRideReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lblSelectRideResQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnRideResQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRideResError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlReserveRideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRideReserve)
                    .addComponent(btnRideCancel))
                .addGap(52, 52, 52))
        );

        getContentPane().add(pnlReserveRide);

        cbSelectShow.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbSelectShow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kate's Komedy Show", "Hytham's Gone Haywire!", "Brandon's Boredom Buster", "Professor Ken's The Floor Is Java" }));

        cbSelectShowReservation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbSelectShowReservation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM", "6:00 PM" }));

        lblReserveShowTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblReserveShowTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserveShowTitle.setText("Reserve a Show");

        lblSelectShow.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectShow.setText("Select a Show:");

        lblSelectShowReservation.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectShowReservation.setText("Select a Show Reservation:");

        btnShowReserve.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnShowReserve.setText("Reserve");
        btnShowReserve.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnShowReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowReserveActionPerformed(evt);
            }
        });

        btnShowCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnShowCancel.setText("Cancel");
        btnShowCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnShowCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCancelActionPerformed(evt);
            }
        });

        lblShowResError.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblShowResError.setForeground(new java.awt.Color(255, 0, 0));
        lblShowResError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowResError.setText("Error Message");

        spnShowResQty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblSelectShowResQty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSelectShowResQty.setText("Show Reservation Quantity:");

        javax.swing.GroupLayout pnlReserveShowLayout = new javax.swing.GroupLayout(pnlReserveShow);
        pnlReserveShow.setLayout(pnlReserveShowLayout);
        pnlReserveShowLayout.setHorizontalGroup(
            pnlReserveShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReserveShowTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addGroup(pnlReserveShowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlReserveShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectShowReservation)
                    .addComponent(lblSelectShow)
                    .addGroup(pnlReserveShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlReserveShowLayout.createSequentialGroup()
                            .addComponent(btnShowCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cbSelectShow, javax.swing.GroupLayout.Alignment.LEADING, 0, 217, Short.MAX_VALUE)
                        .addComponent(cbSelectShowReservation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlReserveShowLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblSelectShowResQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(pnlReserveShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShowResError, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlReserveShowLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(spnShowResQty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlReserveShowLayout.setVerticalGroup(
            pnlReserveShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReserveShowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReserveShowTitle)
                .addGap(24, 24, 24)
                .addComponent(lblSelectShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSelectShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lblSelectShowReservation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSelectShowReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSelectShowResQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnShowResQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowResError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlReserveShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowReserve)
                    .addComponent(btnShowCancel))
                .addGap(51, 51, 51))
        );

        getContentPane().add(pnlReserveShow);

        lblReserveRideTitle1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblReserveRideTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReserveRideTitle1.setText("Reservation Confirmation");

        taActivityReservationInfo.setColumns(20);
        taActivityReservationInfo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taActivityReservationInfo.setRows(5);
        jScrollPane1.setViewportView(taActivityReservationInfo);

        btnMainMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        lblConfirmedReservationInfo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblConfirmedReservationInfo.setText("Confirmed Reservation Information:");

        javax.swing.GroupLayout pnlReservationConfirmationLayout = new javax.swing.GroupLayout(pnlReservationConfirmation);
        pnlReservationConfirmation.setLayout(pnlReservationConfirmationLayout);
        pnlReservationConfirmationLayout.setHorizontalGroup(
            pnlReservationConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationConfirmationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservationConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserveRideTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservationConfirmationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlReservationConfirmationLayout.createSequentialGroup()
                        .addComponent(lblConfirmedReservationInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlReservationConfirmationLayout.setVerticalGroup(
            pnlReservationConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationConfirmationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReserveRideTitle1)
                .addGap(19, 19, 19)
                .addComponent(lblConfirmedReservationInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMainMenu)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(pnlReservationConfirmation);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRideActionPerformed
        this.pnlSelectActivityType.setVisible(false);
        this.pnlReserveRide.setVisible(true);

    }//GEN-LAST:event_btnRideActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        this.pnlSelectActivityType.setVisible(false);
        this.pnlReserveShow.setVisible(true);

    }//GEN-LAST:event_btnShowActionPerformed

    private void btnMainMenuActSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActSelActionPerformed
        NavigationCtrl navCtrl = new NavigationCtrl();
        this.dispose();

    }//GEN-LAST:event_btnMainMenuActSelActionPerformed

    private void btnRideReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRideReserveActionPerformed
        activityCtrl = new ActivityCtrl();
        String activityName;
        String activityType;
        String timeSlot;
        int quant;
        activityName = (String) cbSelectRide.getSelectedItem();
        activityType = "Ride";
        timeSlot = (String) cbSelectRideReservation.getSelectedItem();
        quant = Integer.parseInt(spnRideResQty.getValue().toString());
        
        activityCtrl.createReservationObject(activityType, activityName, timeSlot, quant);
        reservedActivity = activityCtrl.getReservedActivityInformation();
        this.taActivityReservationInfo.append(reservedActivity.toString());
        
        System.out.println(activityName);
        System.out.println(activityType);
        System.out.println(timeSlot);
        System.out.println(quant);    
        
        this.pnlReservationConfirmation.setVisible(true);
        this.pnlReserveRide.setVisible(false);
        
    }//GEN-LAST:event_btnRideReserveActionPerformed

    private void btnRideCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRideCancelActionPerformed
        NavigationCtrl navCtrl = new NavigationCtrl();
        this.dispose();
    }//GEN-LAST:event_btnRideCancelActionPerformed

    private void btnShowReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowReserveActionPerformed
        activityCtrl = new ActivityCtrl();
        String activityName;
        String activityType;
        String timeSlot;
        int quant;
        activityName = (String) cbSelectShow.getSelectedItem();
        activityType = "Show";
        timeSlot = (String) cbSelectShowReservation.getSelectedItem();
        quant = Integer.parseInt(spnShowResQty.getValue().toString());
        activityCtrl.createReservationObject(activityType, activityName, timeSlot, quant);
        reservedActivity = activityCtrl.getReservedActivityInformation();
        
        
        System.out.println(activityName);
        System.out.println(activityType);
        System.out.println(timeSlot);
        System.out.println(quant);                    
      
        this.pnlReservationConfirmation.setVisible(true);
        this.pnlReserveShow.setVisible(false);
    }//GEN-LAST:event_btnShowReserveActionPerformed

    private void btnShowCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCancelActionPerformed
        NavigationCtrl navCtrl = new NavigationCtrl();
        this.dispose();
    }//GEN-LAST:event_btnShowCancelActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        NavigationCtrl navCtrl = new NavigationCtrl();
        this.dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveActivityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveActivityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveActivityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveActivityUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveActivityUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnMainMenu;
    public javax.swing.JButton btnMainMenuActSel;
    public javax.swing.JButton btnRide;
    public javax.swing.JButton btnRideCancel;
    public javax.swing.JButton btnRideReserve;
    public javax.swing.JButton btnShow;
    public javax.swing.JButton btnShowCancel;
    public javax.swing.JButton btnShowReserve;
    public javax.swing.JComboBox<String> cbSelectRide;
    public javax.swing.JComboBox<String> cbSelectRideReservation;
    public javax.swing.JComboBox<String> cbSelectShow;
    public javax.swing.JComboBox<String> cbSelectShowReservation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfirmedReservationInfo;
    private javax.swing.JLabel lblReserveRideTitle;
    private javax.swing.JLabel lblReserveRideTitle1;
    private javax.swing.JLabel lblReserveShowTitle;
    public javax.swing.JLabel lblRideResError;
    private javax.swing.JLabel lblSelectActivityType;
    private javax.swing.JLabel lblSelectRide;
    private javax.swing.JLabel lblSelectRideResQty;
    private javax.swing.JLabel lblSelectRideReservation;
    private javax.swing.JLabel lblSelectShow;
    private javax.swing.JLabel lblSelectShowResQty;
    private javax.swing.JLabel lblSelectShowReservation;
    public javax.swing.JLabel lblShowResError;
    public javax.swing.JPanel pnlReservationConfirmation;
    public javax.swing.JPanel pnlReserveRide;
    public javax.swing.JPanel pnlReserveShow;
    public javax.swing.JPanel pnlSelectActivityType;
    public javax.swing.JSpinner spnRideResQty;
    public javax.swing.JSpinner spnShowResQty;
    public javax.swing.JTextArea taActivityReservationInfo;
    // End of variables declaration//GEN-END:variables
}
